### ISSUE TITLE
Growatt Server Integration

### ISSUE THREAD

**Issue by WiehanVanNiekerk** [AlexxIT/HassWP#26]
Hi, Alex

I'm having troubles with the las release HassWP_2021.6.5 when I try to install Growatt Server integrations.

This is the errror that I get
```
Error while setting up growatt_server platform for sensor
Traceback (most recent call last):
  File "C:\Users\Main Server PC\Desktop\HA\python-3.8.9\lib\site-packages\homeassistant\helpers\entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "C:\Users\Main Server PC\Desktop\HA\python-3.8.9\lib\site-packages\homeassistant\components\growatt_server\sensor.py", line 603, in async_setup_entry
    devices, plant_id = await hass.async_add_executor_job(get_device_list, api, config)
  File "C:\Users\Main Server PC\Desktop\HA\python-3.8.9\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Main Server PC\Desktop\HA\python-3.8.9\lib\site-packages\homeassistant\components\growatt_server\sensor.py", line 590, in get_device_list
    devices = api.device_list(plant_id)
  File "C:\Users\Main Server PC\Desktop\HA\config\deps\Python38\site-packages\growattServer\__init__.py", line 440, in device_list
    return self.plant_info(plant_id)['deviceList']
  File "C:\Users\Main Server PC\Desktop\HA\config\deps\Python38\site-packages\growattServer\__init__.py", line 453, in plant_info
    data = json.loads(response.content.decode('utf-8'))
  File "C:\Users\Main Server PC\Desktop\HA\python-3.8.9\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Main Server PC\Desktop\HA\python-3.8.9\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Main Server PC\Desktop\HA\python-3.8.9\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 19)
```
Thank you!!

**Comment by AlexxIT** [comment]
The problem does not seem to be Windows-related. Some problem with this specific integration
