### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 41: invalid continuation byte

### ISSUE THREAD

**Issue by rplinfo** [AlexxIT/HassWP#4]
I tried to run, but it shows the error below, I tried to run as admim, but it was unsuccessful

2020-12-27 18:30:44 INFO (MainThread) [homeassistant.bootstrap] Config directory: C:\Automação\HassWP_0.116.4\config
2020-12-27 18:30:44 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\Scripts\hass.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\site-packages\homeassistant\__main__.py", line 312, in main
    exit_code = runner.run(runtime_conf)
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\site-packages\homeassistant\runner.py", line 133, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\site-packages\homeassistant\runner.py", line 122, in setup_and_run_hass
    hass = await bootstrap.async_setup_hass(runtime_config)
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\site-packages\homeassistant\bootstrap.py", line 120, in async_setup_hass
    await async_mount_local_lib_path(runtime_config.config_dir)
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\site-packages\homeassistant\bootstrap.py", line 365, in async_mount_local_lib_path
    lib_dir = await async_get_user_site(deps_dir)
  File "C:\Automação\HassWP_0.116.4\python-3.8.5\lib\site-packages\homeassistant\util\package.py", line 121, in async_get_user_site
    lib_dir = stdout.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 41: invalid continuation byte
Pressione qualquer tecla para continuar. . .

**Comment by AlexxIT** [comment]
It don't starts at all or you try to install some integration/component?

**Comment by rplinfo** [comment]
Hello, it doesn't even start up. Searching the net I found that it was an accentuation error, if you look, I put it in a folder with special characters ("C:\Automação") the problem was the characters "ç" and "ã", I removed and initialized successfully.
