### ISSUE TITLE
Emulated Hue config error

### ISSUE THREAD

**Issue by ahouse3761** [AlexxIT/HassWP#50]
Hi, new to HA and have it up and running. I tried to use the emulated hue integration using the following in my configuration.yaml file:

emulated_hue:
  host_ip: 192.168.1.35
  listen_port: 80
  advertise_ip: 10.0.0.10
  advertise_port: 8080
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false
  exposed_domains:
    - light
  entities:
    light.den_art_2b_8c_f7:
      name: "Den art"

But I get an error on restart that I cannot interpret:

Logger: homeassistant.setup
Source: C:\Users\tahou\Home Assistant\HassWP_2022.5.3\python-3.9.10.amd64\lib\site-packages\homeassistant\setup.py:245
First occurred: 5:30:33 PM (1 occurrences)
Last logged: 5:30:33 PM

Error during setup of component emulated_hue
Traceback (most recent call last):
  File "C:\Users\tahou\Home Assistant\HassWP_2022.5.3\python-3.9.10.amd64\lib\site-packages\homeassistant\setup.py", line 235, in _async_setup_component
    result = await task
  File "C:\Users\tahou\Home Assistant\HassWP_2022.5.3\python-3.9.10.amd64\lib\site-packages\homeassistant\components\emulated_hue\__init__.py", line 137, in async_setup
    listen = create_upnp_datagram_endpoint(
  File "C:\Users\tahou\Home Assistant\HassWP_2022.5.3\python-3.9.10.amd64\lib\site-packages\homeassistant\components\emulated_hue\upnp.py", line 73, in create_upnp_datagram_endpoint
    ssdp_socket.setsockopt(
OSError: [WinError 10022] An invalid argument was supplied

Any help appreciated.
Regards,
Allen

**Comment by ahouse3761** [comment]
Is this the wrong place to ask for help with this? I tried the general forum and got no response.
Thx,
Allen

**Comment by Darkstarxx** [comment]
You can ask directly on his Github. I can't even get the new release to executeProperly. February release works fine. Sent from my T-Mobile 5G Device
-------- Original message --------From: ahouse3761 ***@***.***> Date: 5/23/22  10:42 PM  (GMT-05:00) To: AlexxIT/HassWP ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [AlexxIT/HassWP] Emulated Hue config error (Issue #50) 
Is this the wrong place to ask for help with this? I tried the general forum and got no response.
Thx,
Allen

**Comment by AlexxIT** [comment]
This is very complicated python API. Very likely it doesn't supported in Windows
