### ISSUE TITLE
无法启动homekit

### ISSUE THREAD

**Issue by bystart** [AlexxIT/HassWP#69]
Logger: homeassistant.config_entries
Source: D:\HassWP_2023.1.7\python-3.9.10.amd64\lib\site-packages\homeassistant\config_entries.py:462
First occurred: 22:01:26 (1 occurrences)
Last logged: 22:01:26

Error setting up entry HASS Bridge:21064 for homekit
Traceback (most recent call last):
  File "D:\HassWP_2023.1.7\python-3.9.10.amd64\lib\site-packages\homeassistant\config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "D:\HassWP_2023.1.7\python-3.9.10.amd64\lib\site-packages\homeassistant\components\homekit\__init__.py", line 344, in async_setup_entry
    await homekit.async_start()
  File "D:\HassWP_2023.1.7\python-3.9.10.amd64\lib\site-packages\homeassistant\components\homekit\__init__.py", line 792, in async_start
    await self.hass.async_add_executor_job(self.driver.persist)
  File "D:\HassWP_2023.1.7\python-3.9.10.amd64\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\HassWP_2023.1.7\python-3.9.10.amd64\lib\site-packages\pyhap\accessory_driver.py", line 648, in persist
    os.chmod(self.persist_file, 0o644)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'D:\\HassWP_2023.1.7\\config\\.storage\\homekit.627b4ea8ed6a820bd534dfedb3f474e0.state'

**Comment by AlexHow549** [comment]
Same error encountered

**Comment by AlexxIT** [comment]
Maybe fixed in latest versions
