### ISSUE TITLE
Homekit error on HA startup

### ISSUE THREAD

**Issue by Honam9394** [AlexxIT/HassWP#74]
Hi, 

System: Windows 10 - 64 Bit

I cannot get homekit controller integration to work. Error on UI says "Config flow could not be loaded: {"message":"Invalid handler specified"}"

I notice when starting up HA, the the cmd prompt logs has the below error which may be the cause for the integration failure
```
2023-04-21 22:44:32,653.653 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration homekit_controller: DLL load failed while importing chacha20poly1305_reuseable: %1 is not a valid Win32 application.
2023-04-21 22:44:32,660.660 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\config_entries.py", line 958, in async_create_flow
    integration.get_platform("config_flow")
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\components\homekit_controller\__init__.py", line 8, in <module>
    import aiohomekit
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\aiohomekit\__init__.py", line 46, in <module>
    from .controller import Controller
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\aiohomekit\controller\__init__.py", line 19, in <module>
    from .abstract import TransportType
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\aiohomekit\controller\abstract.py", line 28, in <module>
    from aiohomekit.model import Accessories, AccessoriesState, Transport
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\aiohomekit\model\__init__.py", line 24, in <module>
    from aiohomekit.protocol.statuscodes import to_status_code
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\aiohomekit\protocol\__init__.py", line 27, in <module>
    from aiohomekit.crypto import (
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\aiohomekit\crypto\__init__.py", line 25, in <module>
    from .chacha20poly1305 import ChaCha20Poly1305Decryptor, ChaCha20Poly1305Encryptor
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\aiohomekit\crypto\chacha20poly1305.py", line 32, in <module>
    from chacha20poly1305_reuseable import ChaCha20Poly1305Reusable
ImportError: DLL load failed while importing chacha20poly1305_reuseable: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\helpers\discovery_flow.py", line 95, in _async_start
    await gather_with_concurrency(
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\util\async_.py", line 178, in gather_with_concurrency
    return await gather(
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\util\async_.py", line 176, in sem_task
    return await task
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\config_entries.py", line 831, in async_init
    flow, result = await task
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\config_entries.py", line 849, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "C:\HassWP_2023.3.6\python-3.10.9.amd64\lib\site-packages\homeassistant\config_entries.py", line 965, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
```

**Comment by AlexxIT** [comment]
`chacha20poly1305_reuseable` should be fixed in latest versions.
