### ISSUE TITLE
Unable to add homekit bridge

### ISSUE THREAD

**Issue by tarandeepbrar** [AlexxIT/HassWP#79]
Hi,

I am trying to add homekit bridge to my HassWP setup but it fails with the following error. I have tried restarting Home Assistant but it doesn't help. I have tried the following troubleshooting steps but they didn't help:
1. The firewall is disabled on my machine 
2. I have checked no other application is listening on port 21064. 
3. Tried running the hass.cmd under local admin but still the same result.

Any help would be appreciated. Currently running under windows 11.

```
Logger: homeassistant.config_entries
Source: C:\HassWP_2023.5.3\python-3.10.9.amd64\lib\site-packages\homeassistant\config_entries.py:472
First occurred: 10:32:14 PM (2 occurrences) 
Last logged: 10:34:15 PM
Error setting up entry HASS Bridge:21064 for homekit

Traceback (most recent call last):
  File "C:\HassWP_2023.5.3\python-3.10.9.amd64\lib\site-packages\homeassistant\config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "C:\HassWP_2023.5.3\python-3.10.9.amd64\lib\site-packages\homeassistant\components\homekit\__init__.py", line 348, in async_setup_entry
    await homekit.async_start()
  File "C:\HassWP_2023.5.3\python-3.10.9.amd64\lib\site-packages\homeassistant\components\homekit\__init__.py", line 797, in async_start
    await self.driver.async_start()
  File "C:\HassWP_2023.5.3\python-3.10.9.amd64\lib\site-packages\pyhap\accessory_driver.py", line 377, in async_start
    await self.http_server.async_start(self.loop)
  File "C:\HassWP_2023.5.3\python-3.10.9.amd64\lib\site-packages\pyhap\hap_server.py", line 44, in async_start
    self.server = await loop.create_server(
  File "C:\HassWP_2023.5.3\python-3.10.9.amd64\lib\asyncio\base_events.py", line 1513, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 21064): only one usage of each socket address (protocol/network address/port) is normally permitted

```

**Comment by AlexxIT** [comment]
I think should be fixed https://github.com/AlexxIT/HassWP/releases/tag/v2023.12.4
