### ISSUE TITLE
Nabu Casa not connecting

### ISSUE THREAD

**Issue by tobycth3** [AlexxIT/HassWP#83]
Logger: homeassistant.components.cloud.http_api
Source: C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\site-packages\homeassistant\components\cloud\http_api.py:177
Integration: Home Assistant Cloud (documentation, issues)
First occurred: 5:28:01 PM (1 occurrences)
Last logged: 5:28:01 PM

Unexpected error processing request for /api/cloud/login
Traceback (most recent call last):
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\site-packages\homeassistant\components\cloud\http_api.py", line 128, in error_handler
    result = await handler(view, request, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\site-packages\homeassistant\components\http\data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\site-packages\homeassistant\components\cloud\http_api.py", line 227, in post
    await cloud.login(data["email"], data["password"])
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\site-packages\hass_nabucasa\__init__.py", line 223, in login
    await self.auth.async_login(email, password)
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\site-packages\hass_nabucasa\auth.py", line 175, in async_login
    task = await self.cloud.update_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\site-packages\hass_nabucasa\__init__.py", line 168, in update_token
    await self.run_executor(self._write_user_info)
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\site-packages\hass_nabucasa\__init__.py", line 257, in _write_user_info
    self.user_info_path.chmod(0o600)
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\pathlib.py", line 1132, in chmod
    os.chmod(self, mode, follow_symlinks=follow_symlinks)
  File "C:\Users\WMC\Desktop\HassWP_2023.12.4\python-3.11.6.amd64\Lib\site-packages\hass_win\__main__.py", line 142, in wrapper
    if path.endswith(".state"):
       ^^^^^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'endswith'

**Comment by AlexxIT** [comment]
I don't know if I can fix this. Because I don't have NabuCasa account for tests

**Comment by tobycth3** [comment]
I'm not sure the error is limited to just NabuCase, it throws that error any time I try to enable remote access

**Comment by mtoo22** [comment]
Hope this can be resolved.

**Comment by gorfreed** [comment]
I experience the same problem. Seems like the issue was not addressed yet.
